#=====================================================
# Define Box 
#=====================================================

/gate/world/daughters/name             BoxName
/gate/world/daughters/insert            box
/gate/BoxName/placement/setTranslation  0.0 0.0 0.0 m
/gate/BoxName/geometry/setXLength   20 cm
/gate/BoxName/geometry/setYLength   45 cm
/gate/BoxName/geometry/setZLength   35 cm
/gate/BoxName/setMaterial Nylon
/gate/BoxName/vis/setVisible 1
/gate/BoxName/vis/setColor             white

##################### PHYSICS CUTS ######################
#Cut on max step size at least 1/100 thickness of volume being traversed by particles
/gate/physics/Gamma/SetCutInRegion      BoxName 1 mm 
/gate/physics/Electron/SetCutInRegion   BoxName 1 mm
/gate/physics/Positron/SetCutInRegion   BoxName 1 mm

