#=====================================================
# Define Box 
#=====================================================

/gate/world/daughters/name             Detector3
/gate/world/daughters/insert            box
/gate/Detector3/placement/setTranslation  -0.9 0. -0.9 m
/gate/Detector3/placement/setRotationAxis 0 1 0
/gate/Detector3/placement/setRotationAngle 45 deg
/gate/Detector3/geometry/setXLength   5 cm
/gate/Detector3/geometry/setYLength   5 cm
/gate/Detector3/geometry/setZLength   5 cm
/gate/Detector3/setMaterial Germanium
/gate/Detector3/vis/setVisible 1
/gate/Detector3/vis/setColor             white

##################### PHYSICS CUTS ######################
#Cut on max step size at least 1/100 thickness of volume being traversed by particles
/gate/physics/Gamma/SetCutInRegion      Detector3 0.05 mm 
/gate/physics/Electron/SetCutInRegion   Detector3 0.05 mm
/gate/physics/Positron/SetCutInRegion   Detector2 0.05 mm

######################## Output #########################
/gate/actor/addActor                           DoseActor  EnergyDepDet3
/gate/actor/EnergyDepDet3/save                  Detector3.txt
/gate/actor/EnergyDepDet3/attachTo              Detector3 
/gate/actor/EnergyDepDet3/stepHitType           random
/gate/actor/EnergyDepDet3/setPosition           0.0 0.0 0.0 mm #Now in coordinate system of box
/gate/actor/EnergyDepDet3/setSize               5 5 5 cm
/gate/actor/EnergyDepDet3/setResolution         10 10 10 
/gate/actor/EnergyDepDet3/enableEdep            true
/gate/actor/EnergyDepDet3/enableDose            false
/gate/actor/EnergyDepDet3/enableSquaredEdep     false #options not typed are false by default except Dose
/gate/actor/EnergyDepDet3/enableNumberOfHits    false #turn on as required

/gate/actor/addActor                      PhaseSpaceActor PSDetector3
/gate/actor/PSDetector3/save                    Detector3PS.root
/gate/actor/PSDetector3/attachTo                Detector3
/gate/actor/PSDetector3/enableEkine             true
/gate/actor/PSDetector3/enableXDirection        true
/gate/actor/PSDetector3/enableYDirection        true
/gate/actor/PSDetector3/enableZDirection        true
/gate/actor/PSDetector3/enableProductionVolume  true
/gate/actor/PSDetector3/enableProductionProcess true