#=====================================================
# Define Box 
#=====================================================

/gate/world/daughters/name             Phantom1
/gate/world/daughters/insert            cylinder
/gate/Phantom1/placement/setTranslation  50.0 0.0 0.0 cm
/gate/Phantom1/placement/setRotationAxis 1 0 0
/gate/Phantom1/placement/setRotationAngle 90 deg
/gate/Phantom1/geometry/setRmin   0 cm
/gate/Phantom1/geometry/setRmax   12.5 cm
/gate/Phantom1/geometry/setHeight   150 cm
/gate/Phantom1/geometry/setPhiStart 0 deg
/gate/Phantom1/geometry/setDeltaPhi 360 deg
/gate/Phantom1/setMaterial Water
/gate/Phantom1/vis/setVisible 1
/gate/Phantom1/vis/setColor             blue

##################### PHYSICS CUTS ######################
#Cut on max step size at least 1/100 thickness of volume being traversed by particles
/gate/physics/Gamma/SetCutInRegion      Phantom1 0.1 mm 
/gate/physics/Electron/SetCutInRegion   Phantom1 0.1 mm
/gate/physics/Positron/SetCutInRegion   Phantom1 0.1 mm