#=====================================================
# Define Box 
#=====================================================

/gate/world/daughters/name             PSBox3
/gate/world/daughters/insert            box
/gate/PSBox3/placement/setTranslation  3. 0. 0. m
#/gate/PSBox3/placement/setRotationAxis 0 1 0
#/gate/PSBox3/placement/setRotationAngle 45 deg
/gate/PSBox3/geometry/setXLength   5 cm
/gate/PSBox3/geometry/setYLength   5 cm
/gate/PSBox3/geometry/setZLength   5 cm
/gate/PSBox3/setMaterial Air
/gate/PSBox3/vis/setVisible 1
/gate/PSBox3/vis/setColor             white

##################### PHYSICS CUTS ######################
#Cut on max step size at least 1/100 thickness of volume being traversed by particles
/gate/physics/Gamma/SetCutInRegion      PSBox3 0.05 mm 
/gate/physics/Electron/SetCutInRegion   PSBox3 0.05 mm
/gate/physics/Positron/SetCutInRegion   PSBox3 0.05 mm

######################## Output #########################
#/gate/actor/addActor                           DoseActor  EnergyDepDet1
#/gate/actor/EnergyDepDet1/save                  Detector1.txt
#/gate/actor/EnergyDepDet1/attachTo              Detector1 
#/gate/actor/EnergyDepDet1/stepHitType           random
#/gate/actor/EnergyDepDet1/setPosition           0.0 0.0 0.0 mm #Now in coordinate system of box
#/gate/actor/EnergyDepDet1/setSize               5 5 5 cm
#/gate/actor/EnergyDepDet1/setResolution         10 10 10 
#/gate/actor/EnergyDepDet1/enableEdep            true
#/gate/actor/EnergyDepDet1/enableDose            false
#/gate/actor/EnergyDepDet1/enableSquaredEdep     true #options not typed are false by default except Dose
#/gate/actor/EnergyDepDet1/enableNumberOfHits    true #turn on as required

/gate/actor/addActor                      PhaseSpaceActor PS3m
/gate/actor/PS3m/save                    PS3m.root
/gate/actor/PS3m/attachTo                PSBox3
/gate/actor/PS3m/enableEkine             true
/gate/actor/PS3m/enableXDirection        true
/gate/actor/PS3m/enableYDirection        true
/gate/actor/PS3m/enableZDirection        true
/gate/actor/PS3m/enableProductionVolume  true
/gate/actor/PS3m/enableProductionProcess true