#=====================================================
# Define Box 
#=====================================================

/gate/world/daughters/name             PSBox7
/gate/world/daughters/insert            box
/gate/PSBox7/placement/setTranslation  7. 0. 0. m
#/gate/PSBox7/placement/setRotationAxis 0 1 0
#/gate/PSBox7/placement/setRotationAngle 45 deg
/gate/PSBox7/geometry/setXLength   5 cm
/gate/PSBox7/geometry/setYLength   5 cm
/gate/PSBox7/geometry/setZLength   5 cm
/gate/PSBox7/setMaterial Air
/gate/PSBox7/vis/setVisible 1
/gate/PSBox7/vis/setColor             white

##################### PHYSICS CUTS ######################
#Cut on max step size at least 1/100 thickness of volume being traversed by particles
/gate/physics/Gamma/SetCutInRegion      PSBox7 0.05 mm 
/gate/physics/Electron/SetCutInRegion   PSBox7 0.05 mm
/gate/physics/Positron/SetCutInRegion   PSBox7 0.05 mm

######################## Output #########################
#/gate/actor/addActor                           DoseActor  EnergyDepDet1
#/gate/actor/EnergyDepDet1/save                  Detector1.txt
#/gate/actor/EnergyDepDet1/attachTo              Detector1 
#/gate/actor/EnergyDepDet1/stepHitType           random
#/gate/actor/EnergyDepDet1/setPosition           0.0 0.0 0.0 mm #Now in coordinate system of box
#/gate/actor/EnergyDepDet1/setSize               5 5 5 cm
#/gate/actor/EnergyDepDet1/setResolution         10 10 10 
#/gate/actor/EnergyDepDet1/enableEdep            true
#/gate/actor/EnergyDepDet1/enableDose            false
#/gate/actor/EnergyDepDet1/enableSquaredEdep     true #options not typed are false by default except Dose
#/gate/actor/EnergyDepDet1/enableNumberOfHits    true #turn on as required

/gate/actor/addActor                      PhaseSpaceActor PS7m
/gate/actor/PS7m/save                    PS7m.root
/gate/actor/PS7m/attachTo                PSBox7
/gate/actor/PS7m/enableEkine             true
/gate/actor/PS7m/enableXDirection        true
/gate/actor/PS7m/enableYDirection        true
/gate/actor/PS7m/enableZDirection        true
/gate/actor/PS7m/enableProductionVolume  true
/gate/actor/PS7m/enableProductionProcess true