#=====================================================
# Define Box 
#=====================================================

/gate/world/daughters/name             PSBox8
/gate/world/daughters/insert            box
/gate/PSBox8/placement/setTranslation  8. 0. 0. m
#/gate/PSBox8/placement/setRotationAxis 0 1 0
#/gate/PSBox8/placement/setRotationAngle 45 deg
/gate/PSBox8/geometry/setXLength   5 cm
/gate/PSBox8/geometry/setYLength   5 cm
/gate/PSBox8/geometry/setZLength   5 cm
/gate/PSBox8/setMaterial Air
/gate/PSBox8/vis/setVisible 1
/gate/PSBox8/vis/setColor             white

##################### PHYSICS CUTS ######################
#Cut on max step size at least 1/100 thickness of volume being traversed by particles
/gate/physics/Gamma/SetCutInRegion      PSBox8 0.05 mm 
/gate/physics/Electron/SetCutInRegion   PSBox8 0.05 mm
/gate/physics/Positron/SetCutInRegion   PSBox8 0.05 mm

######################## Output #########################
#/gate/actor/addActor                           DoseActor  EnergyDepDet1
#/gate/actor/EnergyDepDet1/save                  Detector1.txt
#/gate/actor/EnergyDepDet1/attachTo              Detector1 
#/gate/actor/EnergyDepDet1/stepHitType           random
#/gate/actor/EnergyDepDet1/setPosition           0.0 0.0 0.0 mm #Now in coordinate system of box
#/gate/actor/EnergyDepDet1/setSize               5 5 5 cm
#/gate/actor/EnergyDepDet1/setResolution         10 10 10 
#/gate/actor/EnergyDepDet1/enableEdep            true
#/gate/actor/EnergyDepDet1/enableDose            false
#/gate/actor/EnergyDepDet1/enableSquaredEdep     true #options not typed are false by default except Dose
#/gate/actor/EnergyDepDet1/enableNumberOfHits    true #turn on as required

/gate/actor/addActor                      PhaseSpaceActor PS8m
/gate/actor/PS8m/save                    PS8m.root
/gate/actor/PS8m/attachTo                PSBox8
/gate/actor/PS8m/enableEkine             true
/gate/actor/PS8m/enableXDirection        true
/gate/actor/PS8m/enableYDirection        true
/gate/actor/PS8m/enableZDirection        true
/gate/actor/PS8m/enableProductionVolume  true
/gate/actor/PS8m/enableProductionProcess true