#=====================================================
# Define Box 
#=====================================================

/gate/world/daughters/name             PSBox9
/gate/world/daughters/insert            box
/gate/PSBox9/placement/setTranslation  9. 0. 0. m
#/gate/PSBox9/placement/setRotationAxis 0 1 0
#/gate/PSBox9/placement/setRotationAngle 45 deg
/gate/PSBox9/geometry/setXLength   5 cm
/gate/PSBox9/geometry/setYLength   5 cm
/gate/PSBox9/geometry/setZLength   5 cm
/gate/PSBox9/setMaterial Air
/gate/PSBox9/vis/setVisible 1
/gate/PSBox9/vis/setColor             white

##################### PHYSICS CUTS ######################
#Cut on max step size at least 1/100 thickness of volume being traversed by particles
/gate/physics/Gamma/SetCutInRegion      PSBox9 0.05 mm 
/gate/physics/Electron/SetCutInRegion   PSBox9 0.05 mm
/gate/physics/Positron/SetCutInRegion   PSBox9 0.05 mm

######################## Output #########################
#/gate/actor/addActor                           DoseActor  EnergyDepDet1
#/gate/actor/EnergyDepDet1/save                  Detector1.txt
#/gate/actor/EnergyDepDet1/attachTo              Detector1 
#/gate/actor/EnergyDepDet1/stepHitType           random
#/gate/actor/EnergyDepDet1/setPosition           0.0 0.0 0.0 mm #Now in coordinate system of box
#/gate/actor/EnergyDepDet1/setSize               5 5 5 cm
#/gate/actor/EnergyDepDet1/setResolution         10 10 10 
#/gate/actor/EnergyDepDet1/enableEdep            true
#/gate/actor/EnergyDepDet1/enableDose            false
#/gate/actor/EnergyDepDet1/enableSquaredEdep     true #options not typed are false by default except Dose
#/gate/actor/EnergyDepDet1/enableNumberOfHits    true #turn on as required

/gate/actor/addActor                      PhaseSpaceActor PS9m
/gate/actor/PS9m/save                    PS9m.root
/gate/actor/PS9m/attachTo                PSBox9
/gate/actor/PS9m/enableEkine             true
/gate/actor/PS9m/enableXDirection        true
/gate/actor/PS9m/enableYDirection        true
/gate/actor/PS9m/enableZDirection        true
/gate/actor/PS9m/enableProductionVolume  true
/gate/actor/PS9m/enableProductionProcess true