/vis/disable
/gate/geometry/setMaterialDatabase GateMaterials.db
/gate/world/geometry/setXLength 14 m
/gate/world/geometry/setYLength 2 m
/gate/world/geometry/setZLength 2 m
/gate/world/setMaterial Air
/gate/physics/addPhysicsList emstandard_opt3
/gate/physics/Gamma/SetCutInRegion world 2 mm
/gate/physics/Electron/SetCutInRegion world 2 mm
/gate/physics/Positron/SetCutInRegion world 2 mm
/gate/world/daughters/name PSBox1
/gate/world/daughters/insert box
/gate/PSBox1/placement/setTranslation 1. 0. 0. m
/gate/PSBox1/geometry/setXLength 5 cm
/gate/PSBox1/geometry/setYLength 5 cm
/gate/PSBox1/geometry/setZLength 5 cm
/gate/PSBox1/setMaterial Air
/gate/PSBox1/vis/setVisible 1
/gate/PSBox1/vis/setColor white
/gate/physics/Gamma/SetCutInRegion PSBox1 0.05 mm
/gate/physics/Electron/SetCutInRegion PSBox1 0.05 mm
/gate/physics/Positron/SetCutInRegion PSBox1 0.05 mm
/gate/actor/addActor PhaseSpaceActor PS1m
/gate/actor/PS1m/save PS1m2.root
/gate/actor/PS1m/attachTo PSBox1
/gate/actor/PS1m/enableEkine true
/gate/actor/PS1m/enableXDirection true
/gate/actor/PS1m/enableYDirection true
/gate/actor/PS1m/enableZDirection true
/gate/actor/PS1m/enableProductionVolume true
/gate/actor/PS1m/enableProductionProcess true

/gate/world/daughters/name PSBox2
/gate/world/daughters/insert box
/gate/PSBox2/placement/setTranslation 2. 0. 0. m
/gate/PSBox2/geometry/setXLength 5 cm
/gate/PSBox2/geometry/setYLength 5 cm
/gate/PSBox2/geometry/setZLength 5 cm
/gate/PSBox2/setMaterial Air
/gate/PSBox2/vis/setVisible 1
/gate/PSBox2/vis/setColor white
/gate/physics/Gamma/SetCutInRegion PSBox2 0.05 mm
/gate/physics/Electron/SetCutInRegion PSBox2 0.05 mm
/gate/physics/Positron/SetCutInRegion PSBox2 0.05 mm
/gate/actor/addActor PhaseSpaceActor PS2m
/gate/actor/PS2m/save PS2m2.root
/gate/actor/PS2m/attachTo PSBox2
/gate/actor/PS2m/enableEkine true
/gate/actor/PS2m/enableXDirection true
/gate/actor/PS2m/enableYDirection true
/gate/actor/PS2m/enableZDirection true
/gate/actor/PS2m/enableProductionVolume true
/gate/actor/PS2m/enableProductionProcess true

/gate/world/daughters/name PSBox3
/gate/world/daughters/insert box
/gate/PSBox3/placement/setTranslation 3. 0. 0. m
/gate/PSBox3/geometry/setXLength 5 cm
/gate/PSBox3/geometry/setYLength 5 cm
/gate/PSBox3/geometry/setZLength 5 cm
/gate/PSBox3/setMaterial Air
/gate/PSBox3/vis/setVisible 1
/gate/PSBox3/vis/setColor white
/gate/physics/Gamma/SetCutInRegion PSBox3 0.05 mm
/gate/physics/Electron/SetCutInRegion PSBox3 0.05 mm
/gate/physics/Positron/SetCutInRegion PSBox3 0.05 mm
/gate/actor/addActor PhaseSpaceActor PS3m
/gate/actor/PS3m/save PS3m2.root
/gate/actor/PS3m/attachTo PSBox3
/gate/actor/PS3m/enableEkine true
/gate/actor/PS3m/enableXDirection true
/gate/actor/PS3m/enableYDirection true
/gate/actor/PS3m/enableZDirection true
/gate/actor/PS3m/enableProductionVolume true
/gate/actor/PS3m/enableProductionProcess true

/gate/world/daughters/name PSBox4
/gate/world/daughters/insert box
/gate/PSBox4/placement/setTranslation 4. 0. 0. m
/gate/PSBox4/geometry/setXLength 5 cm
/gate/PSBox4/geometry/setYLength 5 cm
/gate/PSBox4/geometry/setZLength 5 cm
/gate/PSBox4/setMaterial Air
/gate/PSBox4/vis/setVisible 1
/gate/PSBox4/vis/setColor white
/gate/physics/Gamma/SetCutInRegion PSBox4 0.05 mm
/gate/physics/Electron/SetCutInRegion PSBox4 0.05 mm
/gate/physics/Positron/SetCutInRegion PSBox4 0.05 mm
/gate/actor/addActor PhaseSpaceActor PS4m
/gate/actor/PS4m/save PS4m2.root
/gate/actor/PS4m/attachTo PSBox4
/gate/actor/PS4m/enableEkine true
/gate/actor/PS4m/enableXDirection true
/gate/actor/PS4m/enableYDirection true
/gate/actor/PS4m/enableZDirection true
/gate/actor/PS4m/enableProductionVolume true
/gate/actor/PS4m/enableProductionProcess true

/gate/world/daughters/name PSBox5
/gate/world/daughters/insert box
/gate/PSBox5/placement/setTranslation 5. 0. 0. m
/gate/PSBox5/geometry/setXLength 5 cm
/gate/PSBox5/geometry/setYLength 5 cm
/gate/PSBox5/geometry/setZLength 5 cm
/gate/PSBox5/setMaterial Air
/gate/PSBox5/vis/setVisible 1
/gate/PSBox5/vis/setColor white
/gate/physics/Gamma/SetCutInRegion PSBox5 0.05 mm
/gate/physics/Electron/SetCutInRegion PSBox5 0.05 mm
/gate/physics/Positron/SetCutInRegion PSBox1 0.05 mm
/gate/actor/addActor PhaseSpaceActor PS5m
/gate/actor/PS5m/save PS5m2.root
/gate/actor/PS5m/attachTo PSBox5
/gate/actor/PS5m/enableEkine true
/gate/actor/PS5m/enableXDirection true
/gate/actor/PS5m/enableYDirection true
/gate/actor/PS5m/enableZDirection true
/gate/actor/PS5m/enableProductionVolume true
/gate/actor/PS5m/enableProductionProcess true

/gate/world/daughters/name PSBox6
/gate/world/daughters/insert box
/gate/PSBox6/placement/setTranslation 6. 0. 0. m
/gate/PSBox6/geometry/setXLength 5 cm
/gate/PSBox6/geometry/setYLength 5 cm
/gate/PSBox6/geometry/setZLength 5 cm
/gate/PSBox6/setMaterial Air
/gate/PSBox6/vis/setVisible 1
/gate/PSBox6/vis/setColor white
/gate/physics/Gamma/SetCutInRegion PSBox6 0.05 mm
/gate/physics/Electron/SetCutInRegion PSBox6 0.05 mm
/gate/physics/Positron/SetCutInRegion PSBox6 0.05 mm
/gate/actor/addActor PhaseSpaceActor PS6m
/gate/actor/PS6m/save PS6m2.root
/gate/actor/PS6m/attachTo PSBox6
/gate/actor/PS6m/enableEkine true
/gate/actor/PS6m/enableXDirection true
/gate/actor/PS6m/enableYDirection true
/gate/actor/PS6m/enableZDirection true
/gate/actor/PS6m/enableProductionVolume true
/gate/actor/PS6m/enableProductionProcess true

/gate/world/daughters/name PSBox183c
/gate/world/daughters/insert box
/gate/PSBox183c/placement/setTranslation 1.83 0. 0. m
/gate/PSBox183c/geometry/setXLength 5 cm
/gate/PSBox183c/geometry/setYLength 5 cm
/gate/PSBox183c/geometry/setZLength 5 cm
/gate/PSBox183c/setMaterial Air
/gate/PSBox183c/vis/setVisible 1
/gate/PSBox183c/vis/setColor white
/gate/physics/Gamma/SetCutInRegion PSBox183c 0.05 mm
/gate/physics/Electron/SetCutInRegion PSBox183c 0.05 mm
/gate/physics/Positron/SetCutInRegion PSBox183c 0.05 mm
/gate/actor/addActor PhaseSpaceActor PS183cm
/gate/actor/PS183cm/save PS183cm2.root
/gate/actor/PS183cm/attachTo PSBox183c
/gate/actor/PS183cm/enableEkine true
/gate/actor/PS183cm/enableXDirection true
/gate/actor/PS183cm/enableYDirection true
/gate/actor/PS183cm/enableZDirection true
/gate/actor/PS183cm/enableProductionVolume true
/gate/actor/PS183cm/enableProductionProcess true

/gate/world/daughters/name PSBox129c
/gate/world/daughters/insert box
/gate/PSBox129c/placement/setTranslation 1.29 0. 0. m
/gate/PSBox129c/geometry/setXLength 5 cm
/gate/PSBox129c/geometry/setYLength 5 cm
/gate/PSBox129c/geometry/setZLength 5 cm
/gate/PSBox129c/setMaterial Air
/gate/PSBox129c/vis/setVisible 1
/gate/PSBox129c/vis/setColor white
/gate/physics/Gamma/SetCutInRegion PSBox129c 0.05 mm
/gate/physics/Electron/SetCutInRegion PSBox129c 0.05 mm
/gate/physics/Positron/SetCutInRegion PSBox129c 0.05 mm
/gate/actor/addActor PhaseSpaceActor PS129cm
/gate/actor/PS129cm/save PS129cm2.root
/gate/actor/PS129cm/attachTo PSBox129c
/gate/actor/PS129cm/enableEkine true
/gate/actor/PS129cm/enableXDirection true
/gate/actor/PS129cm/enableYDirection true
/gate/actor/PS129cm/enableZDirection true
/gate/actor/PS129cm/enableProductionVolume true
/gate/actor/PS129cm/enableProductionProcess true

/gate/world/daughters/name PSBox120c
/gate/world/daughters/insert box
/gate/PSBox120c/placement/setTranslation 1.2 0. 0. m
/gate/PSBox120c/geometry/setXLength 5 cm
/gate/PSBox120c/geometry/setYLength 5 cm
/gate/PSBox120c/geometry/setZLength 5 cm
/gate/PSBox120c/setMaterial Air
/gate/PSBox120c/vis/setVisible 1
/gate/PSBox120c/vis/setColor white
/gate/physics/Gamma/SetCutInRegion PSBox120c 0.05 mm
/gate/physics/Electron/SetCutInRegion PSBox120c 0.05 mm
/gate/physics/Positron/SetCutInRegion PSBox120c 0.05 mm
/gate/actor/addActor PhaseSpaceActor PS120cm
/gate/actor/PS120cm/save PS120cm2.root
/gate/actor/PS120cm/attachTo PSBox120c
/gate/actor/PS120cm/enableEkine true
/gate/actor/PS120cm/enableXDirection true
/gate/actor/PS120cm/enableYDirection true
/gate/actor/PS120cm/enableZDirection true
/gate/actor/PS120cm/enableProductionVolume true
/gate/actor/PS120cm/enableProductionProcess true

/gate/world/daughters/name PSBox112c
/gate/world/daughters/insert box
/gate/PSBox112c/placement/setTranslation 1.12 0. 0. m
/gate/PSBox112c/geometry/setXLength 5 cm
/gate/PSBox112c/geometry/setYLength 5 cm
/gate/PSBox112c/geometry/setZLength 5 cm
/gate/PSBox112c/setMaterial Air
/gate/PSBox112c/vis/setVisible 1
/gate/PSBox112c/vis/setColor white
/gate/physics/Gamma/SetCutInRegion PSBox112c 0.05 mm
/gate/physics/Electron/SetCutInRegion PSBox112c 0.05 mm
/gate/physics/Positron/SetCutInRegion PSBox112c 0.05 mm
/gate/actor/addActor PhaseSpaceActor PS112cm
/gate/actor/PS112cm/save PS112cm2.root
/gate/actor/PS112cm/attachTo PSBox112c
/gate/actor/PS112cm/enableEkine true
/gate/actor/PS112cm/enableXDirection true
/gate/actor/PS112cm/enableYDirection true
/gate/actor/PS112cm/enableZDirection true
/gate/actor/PS112cm/enableProductionVolume true
/gate/actor/PS112cm/enableProductionProcess true

/gate/world/daughters/name PSBox105c
/gate/world/daughters/insert box
/gate/PSBox105c/placement/setTranslation 1.05 0. 0. m
/gate/PSBox105c/geometry/setXLength 5 cm
/gate/PSBox105c/geometry/setYLength 5 cm
/gate/PSBox105c/geometry/setZLength 5 cm
/gate/PSBox105c/setMaterial Air
/gate/PSBox105c/vis/setVisible 1
/gate/PSBox105c/vis/setColor white
/gate/physics/Gamma/SetCutInRegion PSBox105c 0.05 mm
/gate/physics/Electron/SetCutInRegion PSBox105c 0.05 mm
/gate/physics/Positron/SetCutInRegion PSBox105c 0.05 mm
/gate/actor/addActor PhaseSpaceActor PS105cm
/gate/actor/PS105cm/save PS105cm2.root
/gate/actor/PS105cm/attachTo PSBox105c
/gate/actor/PS105cm/enableEkine true
/gate/actor/PS105cm/enableXDirection true
/gate/actor/PS105cm/enableYDirection true
/gate/actor/PS105cm/enableZDirection true
/gate/actor/PS105cm/enableProductionVolume true
/gate/actor/PS105cm/enableProductionProcess true

/gate/physics/displayCuts
/gate/run/initialize
/gate/source/addSource Caesium137
/gate/source/Caesium137/gps/type Volume
/gate/source/Caesium137/gps/shape Cylinder
/gate/source/Caesium137/gps/radius 5. cm
/gate/source/Caesium137/gps/halfz 5 cm
/gate/source/Caesium137/gps/centre 0. 0. 0. cm
/gate/source/Caesium137/gps/particle gamma
/gate/source/Caesium137/gps/energytype UserSpectrum
/gate/source/Caesium137/gps/setSpectrumFile /usersc/cc14398/StationarySourceGate/mac/SubMacros/Cs137Discrete.txt
/gate/source/Caesium137/setActivity 37000000. Bq
/gate/source/Caesium137/setForcedHalfLife 951441120. s
/gate/source/Caesium137/gps/angtype iso

/gate/application/setTimeSlice 1.0 s
/gate/application/setTimeStart 0. s
/gate/application/setTimeStop 10. s
/gate/random/setEngineName MersenneTwister

/gate/application/noGlobalOutput
/gate/random/setEngineSeed 1410923545341793741
/gate/application/startDAQCluster 1 2 0 s

