#!/bin/sh 
echo "I am running on" $HOSTNAME 
hostname 
uname -a 
ls -la 

/usr/bin/time --verbose /usr/bin/hdfs dfs -copyFromLocal *.root /user/cc14398/Cs137-10s-28Mar  
/usr/bin/hdfs dfs -copyFromLocal *.txt /user/cc14398/Cs137-10s-28Mar  
rm *.root  
rm *.txt   
